#!/bin/bash --norc

PATH="external/org_linaro_components_toolchain_gcc_6_2/libexec/gcc/arm-linux-gnueabi/6.2.1:$PATH" \
    exec \
    external/org_linaro_components_toolchain_gcc_6_2/bin/arm-linux-gnueabi-gcc \
    "$@"
