cc_library(
    name = "network",
    srcs = [
        "a.cpp",
        "a.h",
    ],
    copts = [
        "-pthread",
    ],
    linkopts = [
        "-lpthread",
    ],
    deps = [
        "@ubus_cpp//:ubus++",
    ],
)
